# Generated by Django 4.2.10 on 2025-04-22 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('google_drive_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreTimezone',
            fields=[
                ('store_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timezone_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(db_index=True, max_length=100)),
                ('timestamp_utc', models.DateTimeField(db_index=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['store_id', 'timestamp_utc'], name='monitoring__store_i_3226e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(db_index=True, max_length=100)),
                ('day_of_week', models.IntegerField()),
                ('start_time_local', models.TimeField()),
                ('end_time_local', models.TimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['store_id', 'day_of_week'], name='monitoring__store_i_f96f53_idx')],
            },
        ),
    ]
